name: Jin-Hong Park
permalink: :year/:month/:day
#permalink: :month/:day/:title
#baseurl: /journal2
#baseurl: https://jinhong-park.github.io/journal2/

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2011
now: 2022
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : jinhon9.park@gmail.com
  github : jinhong-park
  twitter : \@LXeLYMOAqisxe8N

# Links in the navigation, you can modify both link name and link url
nav:
#   Home: "/"
#   Memo: "/memo"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
